### ISSUE TITLE
Complete SAP instance setup in Provide Azure environment

### ISSUE THREAD

**Issue by kthomas** [provideplatform/proUBC#39]
Document ORDERS05 vendor idoc config/automation. Several config steps must be completed in the vendor maintenance to enable SAP purchase orders to generate idocs. need to pull to together the required steps into a script that makes it easily repeatable for new environments we set up.

Upon completion...

Retire MMC server. I currently pay $189/month for access to this server.

proUBC is no longer being updated with the Z100085 namespace, so it's time to find a way to get rid of it.

Only reason we've kept it up to now is because it's the only S/4 system we currently have access to with idoc config and data

**Comment by fleischr** [comment]
MMC access retired. Cloud based access enabled.
