### ISSUE TITLE
Just lost the dot

### ISSUE THREAD

**Issue by sap-peur** [provideplatform/proUBC#67]
In 6fa7ea3cc8ae4a82b1b215f24ce33750c0eaf2db we lost the trailing dot.
https://github.com/provideplatform/proUBC/blob/main/src/zcl_proubc_idochlpr.clas.abap#L569

**Comment by fleischr** [comment]
Thanks for the heads up!

Issue is being corrected in the abaplint-cleanup branch.

**Comment by fleischr** [comment]
Merged some changes. Can you do a new pull to confirm?

**Comment by sap-peur** [comment]
All fine.
You are fast as a 🚀

**Comment by fleischr** [comment]
Thanks!
